### ISSUE TITLE
Generating of new tokens.

### ISSUE THREAD

**Issue by 35ulae** [washedpy/Discord-Authentication-Bot#3]
How do I generate new tokens please?

I tried to add some to tokens.txt file but bot always replied with message saying "Token already used. Please contact an admin :handshake:"

**Comment by samuelmi** [comment]
so I most likely fixed the issue, added some new tokens and it seemed to be fine but I'm getting [this](https://i.imgur.com/cz0ltfl.png) error now. Would be glad for any help.

Log:
 TypeError: Cannot read property 'roles' of undefined
    at sql.get.then.row (/root/Discord-Authentication-Bot/authBot.js:83:78)
    at <anonymous>

**Comment by 35ulae** [comment]
fixed
